### ISSUE TITLE
v0.4.0-alpha.0 Release Checklist Due 2018-09-04

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev-ui#107]
Remaining actions:

* [x]  Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [x] Create release (release manager)
* [x] Update Roadmap (TPM/release manager)
* [x] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by korycunningham** [comment]
Thanks, Nathan. The additional announcements checkbox says it's not applicable - is that no longer the case? Do you know if we had anything in the works for content there, or anything we've done previously that we want to follow? I'll get w/ Dylan on the roadmap update tomorrow morning.

**Comment by dclear** [comment]
Email went out to list and made some updates to the roadmap page. We'll revisit that during grooming / planning. Closing this issue and milestone.
