### ISSUE TITLE
v0.5.0 Release Checklist

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#135]
Remaining actions:

* [x]  Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Social media posts, additional announcements for blog, newsletter, etc
* [x] Create release (release manager)
* [x] Update Roadmap (TPM/release manager)
* [x] Verify that autoupdate is working properly
* [x] Followup issues spun off if we need them. (Rework this process to include Monica's role).

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by alkymst** [comment]
To test the release - https://439-99947022-gh.circle-artifacts.com/0/artifacts/DDEV%20UI-0.5.0.dmg

**Comment by alkymst** [comment]
# Release Notes:

## Public v.0.5.0 Alpha Release

### Prerequisites
[DDEV CLI](https://github.com/drud/ddev/) is installed and properly working.

### Release Notes
- This is an still an early alpha release. We fully expect there to be bugs and we have a backlog of features we are working on. We'll respond as quickly as we can to new requests.
- We would love your suggestions, contributions, and help! Please review our [Guidelines for Contributing](https://github.com/drud/ddev/blob/master/CONTRIBUTING.md).

#### Release Highlights
- Drupal 6 support
- UX and UI Improvements
- Docker and DDEV-cli system checks
- Better alert styling and functionality
- Package Updates
- Fixed Community issue #141

## Known Issues
- This version only supports Mac OS. We are working on getting Linux and Windows support and testing in by hopefully the next major release.
- While existing TYPO3, Drupal 6, and Backdrop sites will work, the Create New Project functionality currently only works from Drupal 6, Drupal 7, Drupal 8, and WordPress. We are working hard on adding support for Typo3, and Backdrop.
- We are still working on the code signature so you’ll need to right-click to bypass Mac security settings when opening the app the first time.

**Comment by alkymst** [comment]
For all the release artifacts - https://circleci.com/gh/drud/ddev-ui/439#artifacts/containers/0

**Comment by alkymst** [comment]
@dclear - We can't  verify that autoupdate is working properly until it's published.

**Comment by dclear** [comment]
@alkymst : I moved that bullet towards the end of the list.

**Comment by dclear** [comment]
Closing this issue / milestone / sprint board
