### ISSUE TITLE
v0.6.0 Release Checklist

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#163]
Remaining actions:

* [ ] Review release (product owner)
* [ ] Approve release (Product Owner, QA Lead, Release manager)
* [ ] Create binaries (any DRUD maintainer)
* [ ] Draft release notes (release manager)
* [ ] Social media announcement, blog, newsletter, etc
* [ ] Create release (release manager)
* [ ] Update Roadmap (TPM/release manager)
* [ ] Verify that autoupdate is working properly
* [ ] Followup issues spun off if we need them.

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.

**Comment by dclear** [comment]
Let Monica and I know when you're ready for release testing, @alkymst

**Comment by alkymst** [comment]
@dclear and @mafriend The 0.6.0 RC is ready for testing - https://github.com/drud/ddev-ui/releases/download/untagged-43d282b79ce4a5138a3f/ddev-ui-0.6.0.dmg

**Comment by rfay** [comment]
I took it for a quick spin: It seems to work fine. Some small oddities befitting of an alpha, don't recommend working them too much.
* The "new" button doesn't work.  
<img width="444" alt="ddev-ui" src="https://user-images.githubusercontent.com/112444/49653386-fce37600-f9f1-11e8-9796-cf4d7f0ed6de.png">

Overall, seems fine. I'll try it with the PR that has minor json additions.

**Comment by unn** [comment]
Is there a changelog I can look over?

**Comment by dclear** [comment]
@alkymst : can you do a pass on the issues on the board at https://github.com/orgs/drud/projects/25 and let us know what's done and included in release for testing? https://github.com/drud/ddev-ui/milestone/6 - thanks!

**Comment by unn** [comment]
This has my approval. Good work.

**Comment by alkymst** [comment]
Randy,

The new button issue is actually more a design issue than anything. If works, it's taking you to the view to create a new project. The issue is it's the same view you land on, or the default index page. We used to have a datagrid style list on the index, but it didn't make sense to have duplicate project lists. So unless you are looking at a project you are seeing the create project view. If you click on new while looking at a project you will see the button works as expected. Need to think this through in the redesign.

**Comment by alkymst** [comment]
Randy,

> For sometime in the future, I still can't figure out selecting the correct directory. Tried "connecting existing" and it ended up creating a subdir. * Didn't understand at all what the "clean container" tab might be for. * "Start new project" with Drupal 6 seems like it will seem silly to people. That said, the defaults don't work out right. It defaults to php 7.1, which is incompatible with D6.

I'm going to look into these issues. As for the D6, you might be right on that. as for the PHP configs, I can setup defaults for each that make more sense. I created a yaml file to handle some of this logic vs putting it in code I'll extend the default container settings for each CMS here - https://github.com/drud/ddev-ui/blob/master/src/resources/InstallProfiles.yaml - Good catch!

**Comment by alkymst** [comment]
As for testing with **drud/ddev#1307 (json additions)** this need to be addressed soon, ideally before your next release then this goes live.

**Comment by mafriend** [comment]
Hey folks! 

I did some regression testing using a macOS running mojave 10.14.1 and here are my findings!
https://cl.ly/c0e021baf09d
https://cl.ly/539577d211db

A few issues were found and those have been filed in the appropriate projects, but no blockers were uncovered during testing (though @alkymst is working on the fix for the php project installation)! We should be good to go whenever that bug is fixed! 

Thanks!

**Comment by dclear** [comment]
ty @mafriend!
