### ISSUE TITLE
2.1-UI-Q4-18: Implement test driver

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#175]
## Key Result Description

Implement test driver (system/code to allow the tests to actually run).

1. Define approach
2. Implement it

## Acceptance Criteria

- [x] required issues stubbed and estimated
- [x] MVP issues added to this epic
- [ ] Reviewed with team

**Comment by cyberswat** [comment]
@alkymst @mafriend @dclear We are deprioritizing a few things in the ddev-ui roadmap in order to focus on the DDEV-Live API.  Before we do that we want to make sure that we have some level of automated testing running so that we aren't completely lost when we come back to UI.  Can you please spend some time getting this issue properly updated and resolved?

**Comment by cyberswat** [comment]
@alkymst @mafriend @dclear We are deprioritizing a few things in the ddev-ui roadmap in order to focus on the DDEV-Live API. Before we do that we want to make sure that we have some level of automated testing running so that we aren't completely lost when we come back to UI. Can you please spend some time getting this issue properly updated and resolved?

**Comment by dclear** [comment]
@alkymst  - i added these as A/C to #58 and hooked it up to this epic KR.  However, it really needs an estimate and broken down issues to make progress trackable. Thanks

<img width="515" alt="screen shot 2018-11-27 at 3 41 16 pm" src="https://user-images.githubusercontent.com/1197912/49116478-e8b5b100-f25a-11e8-9212-ce5f09918de7.png">

**Comment by mafriend** [comment]
@alkymst I can help you break down and estimate the issues! Please just let me know where i can help!

**Comment by dclear** [comment]
@mafriend @alkymst : can you please set up a meeting and plot out what remains on this one this week? This is the main issue that we want to show progress on for UI: https://github.com/drud/ddev-ui/issues/58 . Thanks.
