### ISSUE TITLE
2.2-UI-Q4-18: Define tests required to support testing

### ISSUE THREAD

**Issue by dclear** [drud/ddev-ui#176]
## Key Result Description

2.2-UI-Q4-18: Define [tests required to support testing](https://docs.google.com/document/d/1RbY_3_pDOP-69oEcfeXcfqa9qwI2BPW13avFUw5YirM/edit#heading=h.4woucdstrfw9)

*Note:* Since we are deprioritizing adding in new features for the UI product right now and focusing more on the DDEV Live API, we will only be running a very small, highly critical suite of tests. The suite will be used to check that the very basic and most important functions of the UI product are still intact and behaving as expected. 

Once work has been completed on the API and our goals reassessed for the UI product, we will then begin brining more tests into the automated suite. 

## Acceptance Criteria

- [x] Create epic for capturing scenarios: https://github.com/drud/ddev-ui/issues/186
- [x] PR with most critical scenarios captured: https://github.com/drud/ddev-ui/issues/185
- [ ] TK at a later date: capturing the rest of the UI scenarios (the less critical ones)

**Comment by cyberswat** [comment]
@mafriend You've been designated the owner of this objective and assigned to the ticket, but we don't have any of the requisite items requested in the description to proceed.  Can you spend a bit of time getting this issue updated so that is actionable?

**Comment by mafriend** [comment]
Hey Kevin! I can spend some time today filling this out. Thank you for bringing it to my attention!

**Comment by mafriend** [comment]
@dclear I've taken a stab at filling out the rest of this OKR. Some of the other action items related to this (like adding in the steps, running the tests, setting up the framework) should be captured over in #175 and I'll leave my notes for those items in that PR! Please let me know if this is ambiguous or needs any clarity. Thanks!

**Comment by dclear** [comment]
Thanks @mafriend ; looks good. I've set up [progress and projection tracking here](https://github.com/drud/ddev-ui/issues/139#workspaces/okrs-5b2be8a34ac4df24de08d692/reports?report=release&release=5bd788ea191fc961599a1e71)

**Comment by dclear** [comment]
Per [this comment](https://github.com/drud/ddev-ui/issues/188#issuecomment-442100659), we're calling this KR complete for this quarter with https://github.com/drud/ddev-ui/issues/185 . To be picked up again when development resumes.
