### ISSUE TITLE
v0.1 Release Checklist

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev-ui#21]
Remaining actions:

* [x] Review release (product owner)
* [x] Approve release (product owner and release manager)
* [x] Create binaries (any DRUD maintainer)
* [x] Draft release notes (release manager)
* [x] Draft additional announcements for blog, newsletter, etc (not applicable at the moment)
* [x] Create release (release manager)
* [x] Update any package managers to point to new release (release manager)

For additional background information, please see our [Product Release](https://github.com/drud/community/blob/master/development/product_release.md) instructions here.
