### ISSUE TITLE
Integration and UI Testing 

### ISSUE THREAD

**Issue by rickmanelius** [drud/ddev-ui#58]
## What happened (or feature request):

Updated A/C - 11/27/18

- [x] *DONE*: Cypress NPM Install with scripts setup and tied to make.
- [x] *DONE*: Cypress Sample Test Local
- [ ] *INPROGRESS*: Cypress Sample Test CI
- [ ] *NEW*: Implement First Set of Tests

-----

Given the amount of user interaction on the UI, we probably need a more robust approach for integration testing with sample data.

This epic includes:
- [ ] Direct integration testing between ddev-ui and ddev, with real projects. So for example, a test to create a site would actually create a site and verify that it came up correctly.
- [ ] Testing of any ddev-ui actions that change anything on the filesystem. So for example, if we take any action (like untarring an archive), test to make sure that happened on the filesystem.
- [ ] Actual UI testing.

**Comment by dclear** [comment]
adding @mafriend - this is an epic that contains (some) of the current priorities around testing
